[package]
name = "paficent/enumerator"
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [".vscode", "test", ".gitattributes", ".gitignore", "default.project.json", "dev.project.json", "moonwave.toml", "rokit.toml", "selene.toml"]